### ISSUE TITLE
Plot from pbp-json-gen

### ISSUE THREAD

**Issue by ryjombari** [mbari-org/pbp#12]
This plot will allow the user to verify that the temporal metadata match expectations for a deployment, before calling pbp to process.  Our experience is that the user will successfully get complete results as long as temporal metadata are correct.

I think the ideal time to gather the required daily counts of recorded seconds is right before or after writing the json files, i.e. after the program has already identified the subset of files that have data for that day.  The code addition I imagined would simply be to compute how many seconds from each file are within the boundaries of that day, then sum to total seconds.  With vectors for day and total seconds per day, we would output the plot after all json files are written.

Backing up, I wonder if it makes sense to save the complete array of file {start,end,duration} data that is first collected by pbp-json-gen.  That part of the processing is what takes time, and it would be a valuable, reusable processing metadata product.  At least for testing, it would speed up our testing of plot + json generation.

**Comment by danellecline** [comment]
@ryjombari do you have a plot example for this that you could append here that was generated from Matlab?  That would be helpful for reference.

**Comment by ryjombari** [comment]
For sure.  Here is a simple mock-up.  I think it would be ideal if the time-axis labels were more complete, e.g. YYYY-MM-DD at the start of months, possibly rotated to be perpendicular to the axis if needed to fit enough time labels to clearly show month starts within a year.  Our first example will be a year (2020) of NRS11 data.
![RecordingCoverageExample](https://github.com/mbari-org/pbp/assets/30690718/dca1cbb1-7374-4531-8e0d-9c42148d7bbe)

**Comment by ryjombari** [comment]
And maybe a better Y-axis label would be: Daily Recording Coverage (%)

**Comment by danellecline** [comment]
@ryjombari, this is the beginning of this feature. I will run it again with a formatted X-axis YYYY-MM-DD and output a larger image size. The plot library decided what was best for the size. 
![soundtrap_coverage_2020](https://github.com/user-attachments/assets/0dbdb4c0-ccac-4a43-9e3c-8f865cd52f61)

**Comment by ryjombari** [comment]
Cool, Danelle.  Thanks!

**Comment by ryjombari** [comment]
For the 2020 NRS11 data, I computed temporal coverage from both the json files and the pbp output (number of seconds of data that went into each 1-minute bin are recorded as "effort").  They agree, and both show no diminished coverage during March (as in the plot above).  Below is a plot of [% of day] and a csv of the daily recorded seconds.

**Comment by ryjombari** [comment]
![NRS11_2020_dailyseconds](https://github.com/user-attachments/assets/2d4ae1a5-2668-431f-8603-f0f3e4543009)

**Comment by ryjombari** [comment]
[NRS11_2020_dailyseconds.csv](https://github.com/user-attachments/files/16202238/NRS11_2020_dailyseconds.csv)

**Comment by danellecline** [comment]
@ryjombari Getting closer.   Here is the output with revisions to the coverage calculation per the logic [here](https://github.com/mbari-org/pbp/blob/4b5403dfd4abf9e653c3622991faf3bfed3c778c/pbp/json_generator/gen_abstract.py#L65)

Tell me what else you would like changed before I issue the PR to @carueda to review

daily seconds are off  to your Matlab implementation, slightly...could be due to the handling of the 59:60 second filename bug
[nrs_daily_seconds_20200101_20201231_pbp.csv](https://github.com/user-attachments/files/16276519/nrs_daily_seconds_20200101_20201231_pbp.csv)


|   |   |   |   |
|---|---|---|---|
|7/4/20|86353|86354|-1|
|7/5/20|86352|86351|1|
|||| 
|8/29/20|86351|86352|-1|
|8/30/20|86351|86350|1|
||||
|11/17/20|86348|86349|-1|
|11/18/20|86348|86347|1|
  
![nrs_coverage_20200101_20201231](https://github.com/user-attachments/assets/9493517a-ddb7-41e0-8a45-a532dada8a6a)

**Comment by ryjombari** [comment]
Very nice @danellecline!
